### ISSUE TITLE
EXE На винду

### ISSUE THREAD

**Issue by VAFA0000** [sql-enjoyer/Fl-ruller#1]
![Снимок экрана (1)](https://github.com/user-attachments/assets/ddaadd1b-984f-4f78-8545-1f15234d6bf5)
Прив на винду exe не работает 
пишет приложение не совместимо с вашим пк

**Comment by VAFA0000** [comment]
Твой EXE это не приложение 
это LINUX приложение с расширением .exe

**Comment by sql-enjoyer** [comment]
Привет, я добавил рабочий exe. Спасибо, за обратную связь.
